# Generated by Django 5.1.15 on 2026-03-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the tool', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL identifier (auto‑generated from name)', unique=True)),
                ('description', models.TextField(help_text='Short description shown in the card')),
                ('icon', models.CharField(help_text="FontAwesome icon class, e.g., 'fa-file-contract'", max_length=50)),
                ('url', models.CharField(help_text="Relative URL where the tool lives, e.g., '/policies/questionnaire/'", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this tool from the list')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
