# Generated by Django 5.1.15 on 2026-03-11 08:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='is_free',
            field=models.BooleanField(default=True, help_text='If False, requires payment/subscription'),
        ),
        migrations.AddField(
            model_name='tool',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in KES', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID if using subscriptions', max_length=100),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.CharField(default='fas fa-cog', help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on tools page'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(help_text="Used in URLs, e.g., 'privacy-generator'", unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.CharField(help_text="Relative path like '/policies/questionnaire/' or full URL", max_length=500),
        ),
    ]
