# Generated by Django 5.1.15 on 2026-02-12 14:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional short description shown on category pages', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this category from the storefront', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='e.g. Fire Safety, PPE, Compliance Kits', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name', max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Main category this product belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, help_text='PDF, PNG, JPG, DOCX etc. — max 10MB recommended', null=True, upload_to='products/datasheets/%Y/%m/', verbose_name='Datasheet / Technical Document'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description (supports HTML)', verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary photo shown in catalog and detail page', null=True, upload_to='products/images/%Y/%m/', verbose_name='Main Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from storefront without deleting', verbose_name='Active / Visible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points, e.g. ['KEBS certified', '5-year warranty']", verbose_name='Key Features'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='e.g. ABC Fire Extinguisher – 6kg', max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Selling price in Kenyan Shillings', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (KES)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Unique stock-keeping unit (e.g. FS-EXT-6KG)', max_length=64, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name for clean URLs', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs, e.g. {'Weight': '8.5kg', 'Dimensions': 'Φ180 × H500mm'}", verbose_name='Technical Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Current physical stock level', verbose_name='Stock Quantity'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
    ]
