# Generated by Django 5.1.15 on 2026-03-10 11:05

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number', regex='^(\\+254|0)[0-9]{9}$')])),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('auth_provider', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photo_path)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('SME', 'Small Business'), ('SACCO', 'SACCO'), ('SCHOOL', 'School'), ('CLINIC', 'Clinic'), ('FINANCE', 'Financial Services'), ('NGO', 'Non-Profit'), ('OTHER', 'Other')], max_length=50)),
                ('kra_pin', models.CharField(blank=True, max_length=50)),
                ('business_reg', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('default_payment_method', models.CharField(choices=[('MPESA', 'M-PESA'), ('WALLET', 'Platform Wallet'), ('CARD', 'Credit/Debit Card')], default='MPESA', max_length=20)),
                ('default_mpesa_phone', models.CharField(blank=True, max_length=15)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('auto_pay_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_email', models.EmailField(blank=True, help_text='Where to send payment receipts', max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='accounts_user_set', related_query_name='accounts_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='accounts_user_set', related_query_name='accounts_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('is_trusted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.user')),
            ],
            options={
                'ordering': ['-last_login'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('successful', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='accounts.user')),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('MPESA', 'M-PESA'), ('WALLET', 'Platform Wallet'), ('CARD', 'Credit/Debit Card')], max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^(\\+254|0)[0-9]{9}$')])),
                ('mpesa_verified', models.BooleanField(default=False)),
                ('mpesa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('card_expiry', models.CharField(blank=True, max_length=7)),
                ('wallet_address', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.user')),
            ],
            options={
                'ordering': ['-is_default', '-last_used'],
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('STORE', 'Store Purchase'), ('CMP', 'CMP Subscription'), ('SAAS', 'SaaS Subscription'), ('WALLET', 'Wallet Top-up')], db_index=True, max_length=20)),
                ('service_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt', models.CharField(blank=True, db_index=True, max_length=100)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userpaymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company_name'], name='accounts_us_company_fb2c28_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'device_id'], name='accounts_us_user_id_67c192_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['last_login'], name='accounts_us_last_lo_b3fc48_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['user', 'login_time'], name='accounts_us_user_id_71f696_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['ip_address'], name='accounts_us_ip_addr_9b8fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='accounts_us_user_id_10cc1e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['mpesa_phone'], name='accounts_us_mpesa_p_910f76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpaymentmethod',
            unique_together={('user', 'mpesa_phone')},
        ),
        migrations.AddIndex(
            model_name='usertransaction',
            index=models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_05e064_idx'),
        ),
        migrations.AddIndex(
            model_name='usertransaction',
            index=models.Index(fields=['user', 'service'], name='accounts_us_user_id_196ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='usertransaction',
            index=models.Index(fields=['mpesa_receipt'], name='accounts_us_mpesa_r_27ca66_idx'),
        ),
    ]
