# Generated by Django 5.1.15 on 2026-02-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='SEO: Describe the image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display images')),
                ('is_featured', models.BooleanField(default=False, help_text='Use as additional featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.blogpost')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
